# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'

Layout/AlignHash:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
